# Generated by Django 4.1.3 on 2022-11-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Topic',
        ),
    ]
