# Generated by Django 4.1.3 on 2022-11-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_notes', '0004_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'notes'},
        ),
    ]
